volumes:
  mongodb_data: { driver: local }

services:
  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: http://localhost:3000
      PORT: 3000
    depends_on:
      - mongodb
    expose:
      - 3000
    ports:
      - "0.0.0.0:3000:3000"

  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      ALLOW_EMPTY_PASSWORD: yes

# docker network create rocket.chat
# docker run -e ALLOW_EMPTY_PASSWORD=yes -v mongodb_data:/bitnami/mongodb docker.io/bitnami/mongodb:6.0
#
